pipeline:

  test_build:
    image: docker:18.09
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - apk add --no-cache bash sed grep bc coreutils curl
      - ./ci-build.sh
    when:
      event: push

  scan-clamav:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: clamav
    when:
      event: push

  scan-clamav-rest:
    image: quay.io/ukhomeofficedigital/anchore-submission:latest
    image_name: clamav-rest
    when:
      event: push

  build_clamav:
    image: docker:18.09
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t clamav:$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: [push, tag]

  build_clamav-rest:
    image: docker:18.09
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t clamav-rest:$${DRONE_COMMIT_SHA} clamav-rest
    when:
      branch: master
      event: [push, tag]

  clamav_to_quay:
    image: docker:18.09
    secrets:
      - clamav_repo_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${CLAMAV_REPO_TOKEN} quay.io
      - docker tag clamav:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/clamav:$${DRONE_COMMIT_SHA}
      - docker tag clamav:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/clamav:latest
      - docker push quay.io/ukhomeofficedigital/clamav:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/clamav:latest
    when:
      branch: master
      event: push

  clamav-rest_to_quay:
    image: docker:18.09
    secrets:
      - clamav_repo_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${CLAMAV_REPO_TOKEN} quay.io
      - docker tag clamav-rest:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/clamav-rest:$${DRONE_COMMIT_SHA}
      - docker tag clamav-rest:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/clamav-rest:latest
      - docker push quay.io/ukhomeofficedigital/clamav-rest:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/clamav-rest:latest
    when:
      branch: master
      event: push

  tagged_clamav_to_quay:
    image: docker:18.09
    secrets:
      - clamav_repo_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${CLAMAV_REPO_TOKEN} quay.io
      - docker tag clamav:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/clamav:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/clamav:$${DRONE_TAG}
    when:
      event: tag

  tagged_clamav-rest_to_quay:
    image: docker:18.09
    secrets:
      - clamav_repo_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${CLAMAV_REPO_TOKEN} quay.io
      - docker tag clamav-rest:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/clamav-rest:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/clamav-rest:$${DRONE_TAG}
    when:
      event: tag

